version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: motoboy_postgres
    restart: always
    environment:
      POSTGRES_USER: mb_user
      POSTGRES_PASSWORD: nthO07Gi3t
      POSTGRES_DB: motoboy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
