version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: motoboy_postgres
    restart: always
    environment:
      POSTGRES_USER: mb_user
      POSTGRES_PASSWORD: nthO07Gi3t
      POSTGRES_DB: motoboy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: motoboy_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://mb_user:nthO07Gi3t@postgres:5432/motoboy"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
